name: Build with Emscripten

on:
  workflow_dispatch
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        actions-cache-folder: 'emsdk-cache'

    - name: Download xtensor
      uses: actions/checkout@v4
      with:
        repository: xtensor-stack/xtensor
        path: 'lib'
        sparse-checkout: 'include/xtensor'
        sparse-checkout-cone-mode: false

    - name: Download xtl
      uses: actions/checkout@v4
      with:
        repository: xtensor-stack/xtl
        path: 'lib'
        sparse-checkout: 'include/xlt'
        sparse-checkout-cone-mode: false

    - name: Debug
      working-directory: ./web
      run: >
        get-childitem ../lib

    - name: Build
      working-directory: ./web
      run: >
        em++ --bind -s MODULARIZE=1 -s EXPORT_NAME=FissionOpt -s ALLOW_MEMORY_GROWTH=1
        -o FissionOpt.js -std=c++17 -flto -O3
        Bindings.cpp ../Fission.cpp ../OptFission.cpp ../FissionNet.cpp
        ../OverhaulFission.cpp ../OptOverhaulFission.cpp ../OverhaulFissionNet.cpp
        -I../lib/include
